# Spring properties
spring:
  cloud:
    config:
      server:
        git:
          uri:
            file:///E:/Projects/learning/HomeManagement-GIT/home-local-repo
  application:
    name: config-server

# HTTP Server
server:
  port: 8888   # HTTP (Tomcat) port

